Error in .ddg.record.data(dtype, dname, paste(.ddg.data.dir(), dfile,  : 
  argument "dloc" is missing, with no default
Calls: ddg.run ... <Anonymous> -> .ddg.snapshot.node -> .ddg.record.data
Execution halted
