Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument
Calls: prov.run ... .ddg.parse.commands -> withCallingHandlers -> eval -> eval -> apply
In addition: Warning message:
In .ddg.where(name, parent.env(env), warning) : Can't find foo
Execution halted
